import {test,expect,type Page} from '@playwright/test';
import {createSeed} from '../../src/seed';
import {addMarketExamples} from '../../src/market/model';
import {mkdir} from 'node:fs/promises';
async function setup(page:Page){
 await page.goto('/forum');
 await page.evaluate(s=>localStorage.setItem('sustlink.forum.v1',JSON.stringify(s)),{...addMarketExamples(createSeed()),loggedIn:true});
 await page.goto('/board/market');
 await page.evaluate(()=>document.fonts.ready);
}
test('market list opens full detail, restores browsing and updates counts after saving in detail',async({page})=>{
 await setup(page);
 await expect(page.getByRole('button',{name:'分类',exact:true})).toHaveAttribute('aria-expanded','false');
 await page.getByRole('button',{name:'分类',exact:true}).click();
 await page.getByRole('button',{name:'价格未排序，点击升序'}).click();
 await expect(page).toHaveURL(/price=asc/);
 const card=page.locator('[data-product="market-demo-0"]');
 await card.scrollIntoViewIfNeeded();
 await expect(card.getByRole("button")).toHaveCount(0);
 await expect(card.locator(".market-byline")).toContainText("12 已收藏");
 const y=await page.locator('#forum-main').evaluate(e=>e.scrollTop);
 await card.locator('.market-product-link').click();
 await expect(page).toHaveURL(/topic\/market-demo-0/);
 await expect(page.locator('.market-detail')).toBeVisible();
 await expect(page.locator('dialog[open]')).toHaveCount(0);
 await page.locator('.original-post .reaction-save').click();
 await expect(page.getByRole('button',{name:'已收藏',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.locator('.compose-back').click();
 await expect(page).toHaveURL(/price=asc/);
 await expect.poll(()=>page.locator('#forum-main').evaluate(e=>e.scrollTop)).toBeCloseTo(y,0);
 await expect(card.locator('.market-byline')).toContainText('13 已收藏');
});
test('seller comment permissions and public replies share forum storage',async({page})=>{
 await setup(page);await page.goto('/topic/market-demo-1');
 await expect(page.getByText('卖家已关闭公开留言，可通过「聊一聊」咨询。')).toBeVisible();
 await expect(page.locator('.reply-editor')).toHaveCount(0);
 await page.goto('/topic/market-demo-6');
 await page.getByLabel('仅卖家可留言',{exact:true}).check();
 await page.getByLabel('回复内容',{exact:true}).fill('补充：封面有折痕');
 await page.getByRole('button',{name:'发布回复',exact:true}).click();
 await page.reload();
 await expect(page.getByLabel('仅卖家可留言',{exact:true})).toBeChecked();
 await expect(page.locator('.reply-floor')).toContainText('补充：封面有折痕');
 await page.goto('/topic/market-demo-0');
 await page.getByLabel('回复内容',{exact:true}).fill('有配件吗？');
 await page.getByRole('button',{name:'发布回复',exact:true}).click();
 await expect(page.locator('.reply-floor')).toContainText('有配件吗？');
});
test('chat product summary returns to details and restores unsent draft and chat scroll',async({page})=>{
 await setup(page);await page.goto('/topic/market-demo-0');
 await page.getByRole('link',{name:'聊一聊',exact:true}).click();
 await expect(page.locator('.chat-history')).toContainText('先和卖家打个招呼吧');
 await expect(page.locator('.chat-message')).toHaveCount(0);
 await page.getByLabel('消息',{exact:true}).fill('书还在吗？');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 await expect(page.locator('.chat-message')).toHaveCount(1);
 for(let n=0;n<5;n++)await page.getByRole('button',{name:'模拟卖家回复',exact:true}).click();
 await page.getByLabel('消息',{exact:true}).fill('明天下午可以吗');
 await page.locator('.chat-history').evaluate(e=>{e.scrollTop=80;e.dispatchEvent(new Event('scroll'))});
 await page.locator('.chat-product').click();
 await expect(page).toHaveURL(/topic\/market-demo-0/);
 await page.getByRole('link',{name:'聊一聊',exact:true}).click();
 await expect(page.getByLabel('消息',{exact:true})).toHaveValue('明天下午可以吗');
 await expect.poll(()=>page.locator('.chat-history').evaluate(e=>e.scrollTop)).toBe(80);
 await page.reload();
 await expect(page.getByLabel('消息',{exact:true})).toHaveValue('明天下午可以吗');
 await expect(page.locator('.chat-message')).toHaveCount(6);
 await expect(page.locator('.chat-message-meta').first()).not.toContainText('·');
 await page.getByRole('link',{name:'返回',exact:true}).click();
 await expect(page).toHaveURL(/topic\/market-demo-0/);
 await expect(page.locator('.market-detail')).toBeVisible();
 await page.locator('#forum-main > .breadcrumb').click();
 await expect(page).toHaveURL(/\/board\/market$/);
 await page.goto('/messages');await expect(page.locator('.conversation-list')).toContainText('[草稿] 明天下午可以吗');
});

test('chat returns through detail to the original market filters and reading position',async({page})=>{
 await setup(page);
 await page.getByRole('button',{name:'分类',exact:true}).click();
 await page.getByRole('button',{name:'价格未排序，点击升序'}).click();
 const card=page.locator('[data-product="market-demo-0"] .market-product-link');
 await card.scrollIntoViewIfNeeded();
 const y=await page.locator('#forum-main').evaluate(e=>e.scrollTop);
 await card.click();
 await expect(page.locator('.detail-heading h1')).toHaveCSS('font-size','20px');
 await expect(page.locator('.original-post .post-body')).toHaveCSS('line-height','24px');
 await expect(page.locator('.original-post .post-body > p').first()).toHaveCSS('line-height','24px');
 await expect(page.locator('.original-post .post-body > p').nth(1)).toHaveCSS('margin-top','8px');
 await page.getByRole('link',{name:'聊一聊',exact:true}).click();
 await page.reload();
 await page.getByRole('link',{name:'返回',exact:true}).click();
 await expect(page).toHaveURL(/\/topic\/market-demo-0$/);
 await page.getByRole('button',{name:'返回',exact:true}).click();
 await expect(page).toHaveURL(/\/board\/market\?price=asc$/);
 await expect.poll(()=>page.locator('#forum-main').evaluate(e=>e.scrollTop)).toBeCloseTo(y,0);
 await page.goto('/board/life');
 await page.locator('.topic-title').first().click();
 await expect(page.locator('.original-post .post-body')).toHaveCSS('line-height','24px');
});
test('desktop independent columns and mobile single column remain usable',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await setup(page);await mkdir('artifacts/market-integration',{recursive:true});
 await page.screenshot({path:'artifacts/market-integration/home-desktop.png',fullPage:true});
 await page.locator('#forum-main').evaluate(e=>e.scrollTop=700);
 const left=await page.locator('.left-sidebar').boundingBox();
 await page.locator('#forum-main').evaluate(e=>e.scrollTop=900);
 expect((await page.locator('.left-sidebar').boundingBox())!.y).toBeCloseTo(left!.y,0);
 for(const width of [1468,1024,655,390]){
  await page.setViewportSize({width,height:898});
  await page.goto('/board/market');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  if(width<760)await expect(page.locator('.left-sidebar')).toBeHidden();
  await page.screenshot({path:`artifacts/market-integration/home-${width}.png`,fullPage:true});
  await page.goto('/topic/market-demo-0');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:`artifacts/market-integration/detail-${width}.png`,fullPage:true});
 }
 await page.getByRole('link',{name:'聊一聊',exact:true}).click();
 await page.getByLabel('消息',{exact:true}).fill('你好，明天下午方便面交吗？');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 await page.getByRole('button',{name:'模拟卖家回复',exact:true}).click();
 await page.screenshot({path:'artifacts/market-integration/chat-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
