import fs from 'node:fs';
const file = new URL('./app.js',import.meta.url);
let source=fs.readFileSync(file,'utf8');
function replaceFunction(name,body){const re=new RegExp('^function '+name+'\\([^\\n]*$','m');if(!re.test(source))throw Error(name+' missing');source=source.replace(re,()=>body)}
replaceFunction('grid',`function grid(items,market=false){return items.length?\`<div class="posts-grid">\${items.map(p=>card(p,market)).join('')}</div>\`:empty('暂时没有相关内容','换个分类或关键词试试。')}`);
replaceFunction('renderNav',`function renderNav(){const items=[['home','home','首页'],['market','market','集市'],['publish','plus','发布'],['messages','chat','消息'],['profile','user','我的']];nav.hidden=!['home','market','messages','profile'].includes(route.page);if(!nav.children.length)nav.innerHTML=items.map(([page,ic,label])=>\`<button class="nav-item" data-action="nav" data-page="\${page}" aria-label="\${label}">\${page==='publish'?\`<span class="publish-icon">\${icon(ic)}</span>\`:icon(ic)}\${page==='publish'?'':\`<span class="nav-label" aria-hidden="true">\${label}</span>\`}\${page==='messages'?'<span class="badge" aria-hidden="true">2</span>':''}</button>\`).join('');nav.querySelectorAll('.nav-item').forEach(b=>{const active=b.dataset.page===route.page;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}`);
replaceFunction('renderHome',`function renderHome(){const list=posts.filter(p=>category==='全部'||p.tag===category);return \`<header class="topbar original-header"><button class="icon-btn header-square" data-action="nav" data-page="ai" aria-label="打开校园 AI">\${icon('star')}</button><form class="home-search" id="home-search-form"><label class="home-search-box">\${icon('search')}<input id="home-search-input" aria-label="首页搜索内容" placeholder="搜索内容…" autocomplete="off" enterkeyhint="search"></label></form><button class="icon-btn header-square" data-action="home-search" aria-label="搜索校园内容">\${icon('search')}</button></header><div class="category-shell"><div class="categories text-categories" aria-label="内容分类" role="tablist">\${['全部','校园','学习','美食','搭子','运动','社团','旅行'].map(t=>\`<button class="chip \${category===t?'active':''}" role="tab" aria-selected="\${category===t}" data-action="category" data-value="\${t}">\${t}</button>\`).join('')}</div>\${btn('chevron','展开所有分类','category-menu','category-expand')}</div><div class="scroll feed">\${grid(list)}</div>\`}`);
replaceFunction('renderProfile',`function renderProfile(){const filtered=profileTab==='笔记'?posts.filter(p=>p.mine):profileTab==='收藏'?posts.filter(p=>saves.has(p.id)):profileTab==='赞过'?posts.filter(p=>likes.has(p.id)):profileTab==='闲置'?posts.filter(p=>p.mine&&p.tag==='闲置'):posts.filter(p=>p.mine&&p.tag==='搭子');return \`<div class="scroll"><section class="profile-hero original-profile"><div class="profile-toolbar"><span class="spacer"></span><button class="secondary edit-profile" data-action="nav" data-page="edit">\${icon('edit')}<span>编辑资料</span></button>\${btn('menu','个人菜单','profile-menu')}</div><div class="identity"><div class="big-avatar">\${avatarSvg}</div><div class="user-meta"><h1>\${esc(profile.name)}</h1><small>ID: 1516772475</small><small>陕西 · 陕西科技大学</small></div></div><div class="bio-panel"><p class="bio">\${esc(profile.bio)}</p></div></section><div class="profile-tabs" role="tablist" aria-label="个人内容">\${['笔记','收藏','赞过','闲置','搭子'].map(t=>\`<button role="tab" aria-selected="\${profileTab===t}" class="line-tab \${profileTab===t?'active':''}" data-action="profile-tab" data-value="\${t}">\${t}</button>\`).join('')}\${btn('search','搜索我的内容','profile-search')}</div><section class="profile-content">\${filtered.length?grid(filtered,profileTab==='闲置'):empty(profileTab==='收藏'?'还没有收藏的笔记':\`还没有\${profileTab}内容\`,profileTab==='收藏'?'打开笔记，点击星星就能收藏。':'去首页逛逛，或记录你的第一条内容。')}</section></div>\`}`);
replaceFunction('render',`function render(){const previous=captureIndicators();screen.className=route.page==='ai'?'ai-screen':'';const views={home:renderHome,market:renderMarket,profile:renderProfile,search:renderSearch,ai:renderAI,detail:renderDetail,messages:renderMessages,chat:renderChat,publish:renderPublish,edit:renderEdit,collection:renderCollection};screen.innerHTML=(views[route.page]||renderHome)();renderNav();const scroller=screen.querySelector('.scroll');if(scroller)scroller.scrollTop=scrollPositions[routeKey()]||0;screen.querySelectorAll('.cover img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true},{once:true}));if(route.page==='publish')screen.querySelector('#post-title').value=publishDraft.title;updateIndicators(previous);if(scroller&&!matchMedia('(prefers-reduced-motion: reduce)').matches)scroller.animate([{opacity:.65,transform:'translateY(3px)'},{opacity:1,transform:'translateY(0)'}],{duration:200,easing:'cubic-bezier(.22,1,.36,1)'});if(route.page==='ai'||route.page==='chat')scrollChat()}`);
// 同页筛选只动画内容，移动指示条通过旧/新位置衔接。
source=source.replace("case 'category':category=v;scrollPositions.home=0;render();break;","case 'category':category=v;scrollPositions.home=0;if(sheet.open)sheet.close();render();break;");
source=source.replace("case 'market-category':marketCategory=v;render();break;","case 'market-category':marketCategory=v;render();break;");
// 保留灰色卡片内容的完整统一底色，不更改数据与按钮关系。
source=source.replace("if(e.target.id==='search-form')submitSearch", "if(e.target.id==='home-search-form'){openHomeSearch();return}if(e.target.id==='search-form')submitSearch");
source=source.replace("<button class=\"menu-choice\" data-action=\"about\">", "<button class=\"menu-choice\" data-action=\"collection\" data-value=\"market\">${icon('market')}我的闲置</button><button class=\"menu-choice\" data-action=\"nav\" data-page=\"messages\">${icon('users')}我的搭子</button><button class=\"menu-choice\" data-action=\"about\">");
const additions=`
// 固定宽度的移动下划线，使用 transform，不动画布局尺寸。
function indicatorGroups(){return [...screen.querySelectorAll('.categories,.profile-tabs,.home-tabs')]}
function groupKey(el){return route.page+':'+(el.classList.contains('profile-tabs')?'profile':el.classList.contains('home-tabs')?'home':'category')}
function captureIndicators(){const result={};indicatorGroups().forEach(el=>{const line=el.querySelector('.tab-indicator');if(line)result[groupKey(el)]={left:line.getBoundingClientRect().left-el.getBoundingClientRect().left+el.scrollLeft,scroll:el.scrollLeft}});return result}
function updateIndicators(previous={}){indicatorGroups().forEach(el=>{el.style.position='relative';const active=el.querySelector('.active');if(!active)return;const key=groupKey(el),old=previous[key];if(old)el.scrollLeft=old.scroll;let line=el.querySelector('.tab-indicator');if(!line){line=document.createElement('span');line.className='tab-indicator';line.setAttribute('aria-hidden','true');el.append(line)}const r=active.getBoundingClientRect(),g=el.getBoundingClientRect();let x=r.left-g.left+el.scrollLeft+(r.width-24)/2;line.style.transform='translateX('+x+'px)';if(old&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&Math.abs(old.left-x)>1)line.animate([{transform:'translateX('+old.left+'px)'},{transform:'translateX('+x+'px)'}],{duration:260,easing:'cubic-bezier(.22,1,.36,1)'});if(r.right>g.right||r.left<g.left)el.scrollTo({left:Math.max(0,active.offsetLeft-(el.clientWidth-active.offsetWidth)/2),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})})}
function openHomeSearch(){const value=document.getElementById('home-search-input')?.value.trim()||'';query=value;searchMode=false;searchScope='all';navigate('search');if(value)submitSearch(value)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='home-search')openHomeSearch();if(b.dataset.action==='category-menu')modal('全部分类','<div class="category-options">'+['全部','校园','学习','美食','搭子','运动','社团','旅行'].map(t=>'<button class="pill" data-action="category" data-value="'+t+'">'+t+'</button>').join('')+'</div>','<button class="secondary" data-action="close-sheet">关闭</button>')});
let indicatorResize;window.addEventListener('resize',()=>{cancelAnimationFrame(indicatorResize);indicatorResize=requestAnimationFrame(()=>updateIndicators())});
`;
// 函数声明提升；初次 render 之前即可使用，事件绑定放尾部。
source+='\n'+additions;
fs.writeFileSync(file,source);
